### ISSUE TITLE
Le textarea du document uploadé ne laisse pas entrevoir les autres valeurs de saisie

### ISSUE THREAD

**Issue by oncletom** [betagouv/signup-back#248]
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/138627/124444397-d723d680-dd7e-11eb-829f-0b92ae67b5cb.png">

Et magie, quand je déroule la textarea…

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/138627/124444543-fe7aa380-dd7e-11eb-8e1c-6c6c8ccfe11e.png">

**Comment by rdubigny** [comment]
Hello @oncletom !

Pour une implémentation rapide, n'hésites pas à venir faire une PR si tu as une idée précise de ce que tu veux.

Le code correspondant est ici : https://github.com/betagouv/signup-front/blob/c3abde887a975901a0806b1151ce7186f3c02b88/src/components/organisms/form-sections/cartobio-sections/DonneesSection.js#L26-L40

Tu peux installer un mini env de dev via les instructions suivantes : https://github.com/betagouv/signup-front#avec-un-backend-distant (attention ne fonctionne pas avec Chrome en ce moment)
